var FoodName = [
    { name: 'burger', state: false, calories: 497, KcalByNight: 990},
    { name: 'macaron', state: false, calories: 120, KcalByNight: 260 },
    { name: 'ananas', state: true, calories: 50, KcalByNight: 100 },
    { name: 'brocolie', state: true, calories: 34, KcalByNight: 68 },
    { name: 'chickenwings', state: false, calories: 203, KcalByNight: 406 },
    { name: 'chinois', state: false, calories: 138, KcalByNight: 276 },
    { name: 'churros', state: false, calories: 116, KcalByNight: 226 },
    { name: 'coffee', state: false, calories: 0, KcalByNight: 5 },
    { name: 'donut', state: false, calories: 259, KcalByNight: 518 },
    { name: 'fraise', state: true, calories: 29, KcalByNight: 58 },
    { name: 'frites', state: false, calories: 312, KcalByNight: 624 },
    { name: 'glace', state: false, calories: 207, KcalByNight: 414 },
    { name: 'cakechocofraise', state: false, calories: 371, KcalByNight: 742     },
    { name: 'cheesecakefraise', state: false, calories: 321, KcalByNight: 642 },
    { name: 'cookieframb', state: false, calories: 502, KcalByNight: 1004 },
    { name: 'cupcakefraise', state: false, calories: 305, KcalByNight: 610 },
    { name: 'fraisier', state: false, calories: 262, KcalByNight: 524 },
    { name: 'gateaufraise', state: false, calories: 252, KcalByNight: 504 },
    { name: 'gauffregrose', state: false, calories: 291, KcalByNight: 582 },
    { name: 'macaronfraise', state: false, calories: 100, KcalByNight: 200 },
    { name: 'rouleefraise', state: false, calories: 257, KcalByNight: 514 },
    { name: 'tartefraise', state: false, calories: 320, KcalByNight: 640 },
    { name: 'tartemeringueefraise', state: false, calories: 362, KcalByNight: 722 },

    { name: 'ail', state: true, calories: 149, KcalByNight: 149 },
    { name: 'asperge', state: true, calories: 20, KcalByNight: 20 },
    { name: 'aubergine', state: true, calories: 25, KcalByNight: 25 },
    { name: 'brocoli', state: true, calories: 34, KcalByNight: 34 },
    { name: 'carotte', state: true, calories: 41, KcalByNight: 41 },
    { name: 'champi', state: true, calories: 22, KcalByNight: 22 },
    { name: 'choufleur', state: true, calories: 25, KcalByNight: 25 },
    { name: 'chourave', state: true, calories: 27, KcalByNight: 27 },
    { name: 'chourouge', state: true, calories: 31, KcalByNight: 31 },
    { name: 'concombre', state: true, calories: 16, KcalByNight: 16 },
    { name: 'blette', state: true, calories: 19, KcalByNight: 19 },
    { name: 'mais', state: true, calories: 365, KcalByNight: 365 },
    { name: 'oignon', state: true, calories: 40, KcalByNight: 40 },
    { name: 'oignonrouge', state: true, calories: 32, KcalByNight: 32 },
    { name: 'pdt', state: true, calories: 77, KcalByNight: 77 },
    { name: 'pdt2', state: true, calories: 27, KcalByNight: 27 },
    { name: 'petitpois', state: true, calories: 80, KcalByNight: 80 },
    { name: 'piment', state: true, calories: 40, KcalByNight: 40 },
    { name: 'poireau', state: true, calories: 61, KcalByNight: 61 },
    { name: 'poivron', state: true, calories: 20, KcalByNight: 20 },
    { name: 'poivronjaune', state: true, calories: 27, KcalByNight: 27 },
    { name: 'radis', state: true, calories: 16, KcalByNight: 16 },
    { name: 'betterave', state: true, calories: 19, KcalByNight: 19 },
    { name: 'tomate', state: true, calories: 18, KcalByNight: 18 },

    { name: 'beignet', state: false, calories: 400, KcalByNight: 800 },
    { name: 'bolo', state: false, calories: 140, KcalByNight: 280 },
    { name: 'cookie', state: false, calories: 502, KcalByNight: 1004 },
    { name: 'croissant', state: false, calories: 406, KcalByNight: 816 },
    { name: 'croisschoco', state: false, calories: 416, KcalByNight: 832 },
    { name: 'croque', state: false, calories: 390, KcalByNight: 780 },
    { name: 'cupxmas', state: false, calories: 315, KcalByNight: 630 },
    { name: 'donutrose', state: false, calories: 452, KcalByNight: 904 },
    { name: 'entrecote', state: false, calories: 203, KcalByNight: 406 },
    { name: 'guacamole', state: false, calories: 147, KcalByNight: 294 },
    { name: 'hotdog', state: false, calories: 290, KcalByNight: 580 },
    { name: 'maki', state: false, calories: 250, KcalByNight: 500 },
    { name: 'muffinchoco', state: false, calories: 377, KcalByNight: 754 },
    { name: 'pain2', state: false, calories: 265, KcalByNight: 530 },
    { name: 'petitpain', state: false, calories: 322, KcalByNight: 644 },
    { name: 'pizza', state: false, calories: 532, KcalByNight: 1064 },
    { name: 'poulet', state: false, calories: 239, KcalByNight: 478 },
    { name: 'roti', state: false, calories: 240, KcalByNight: 480 },
    { name: 'saucisse', state: false, calories: 301, KcalByNight: 602 },
    { name: 'sushi', state: false, calories: 50, KcalByNight: 100 },
    { name: 'tacos', state: false, calories: 226, KcalByNight: 452 },

    { name: 'amande', state: true, calories: 161, KcalByNight: 161 },
    { name: 'banane', state: true, calories: 89, KcalByNight: 89 },
    { name: 'cerise', state: true, calories: 50, KcalByNight: 50 },
    { name: 'tomate', state: true, calories: 18, KcalByNight: 18 },
    { name: 'fraise', state: true, calories: 33, KcalByNight: 33 },
    { name: 'framboise', state: true, calories: 53, KcalByNight: 53 },
    { name: 'mure', state: true, calories: 45, KcalByNight: 45 },
    { name: 'myrtille', state: true, calories: 60, KcalByNight: 60 },
    { name: 'noisette', state: true, calories: 628, KcalByNight: 628 },
    { name: 'noix', state: true, calories: 654, KcalByNight: 654 },
    { name: 'noix2', state: true, calories: 567, KcalByNight: 567 },
    { name: 'pain', state: true, calories: 284, KcalByNight: 284 },
    { name: 'pasteque', state: true, calories: 31, KcalByNight: 31 },
    { name: 'pistache', state: true, calories: 170, KcalByNight: 170 },
    { name: 'pomme', state: true, calories: 52, KcalByNight: 52 },
    { name: 'raisin', state: true, calories: 67, KcalByNight: 67 },

    { name: 'citron', state: true, calories: 22, KcalByNight: 22 },
    { name: 'melon', state: true, calories: 34, KcalByNight: 34 },
    { name: 'orange', state: true, calories: 47, KcalByNight: 47 },
    { name: 'poire', state: true, calories: 60, KcalByNight: 60 },

    { name: 'biscuits', state: false, calories: 353, KcalByNight: 706 },
    { name: 'brochette', state: false, calories: 105, KcalByNight: 210 },
    { name: 'chips', state: false, calories: 536, KcalByNight: 1072 },
    { name: 'miel', state: false, calories: 304, KcalByNight: 608 },
    { name: 'nouilles', state: false, calories: 138, KcalByNight: 276 },
    { name: 'sauce', state: false, calories: 112, KcalByNight: 222 },
    { name: 'sucette', state: false, calories: 50, KcalByNight: 100 },
    { name: 'sushi2', state: false, calories: 50, KcalByNight: 100 },
    { name: 'sushi3', state: false, calories: 156, KcalByNight: 312 },


];